### ISSUE TITLE
在IOS低版本中不兼容

### ISSUE THREAD

**Issue by imRz1015** [jaweii/Vueg----page-transition-plugin#44]
测试发现在IOS8.X  不兼容，可能造成整个项目崩掉打不开的情况

**Comment by jaweii** [comment]
我没有iOS8.x的设备，所以不打算处理这个问题。
你可以fork下来自己调试看看。

**Comment by imRz1015** [comment]
> 我没有iOS8.x的设备，所以不打算处理这个问题。
> 你可以fork下来自己调试看看。

**Comment by imRz1015** [comment]
> 我没有iOS8.x的设备，所以不打算处理这个问题。
> 你可以fork下来自己调试看看。

我重新拉了一个分支...解决了这个问题。
如果其他朋友看到可以到我仓库瞅一眼
