### ISSUE TITLE
touchPoint 不起作用

### ISSUE THREAD

**Issue by linrufeng** [jaweii/Vueg----page-transition-plugin#46]
const options = {
  duration: '0.2', //转场动画时长，默认为0.3，单位秒
  firstEntryDisable: true, //值为true时禁用首次进入应用时的渐现动画，默认为false
  firstEntryDuration: '.3', //首次进入应用时的渐现动画时长，默认为.6
  forwardAnim: 'touchPoint', //前进动画，默认为fadeInRight
  backAnim: 'touchPoint', //后退动画，默认为fedeInLeft
  sameDepthDisable: false, //url深度相同时禁用动画，默认为false
  tabs: [], //默认为[]，'name'对应路由的name,以实现类似app中点击tab页面水平转场效果，如tabs[1]到tabs[0]，会使用backAnim动画，tabs[1]到tabs[2]，会使用forwardAnim动画
  tabsDisable: false, //值为true时，tabs间的转场没有动画，默认为false
  shadow: false, //值为false，转场时没有阴影的层次效果
  disable: false, //禁用转场动画，默认为false，嵌套路由默认为true
};

Vue.use(vueg, router, options);
我这样配置的，这个效果不起作用，请大神指点

**Comment by jaweii** [comment]
你这是老版本的配置。
请查看最新文档， 或指定vueg版本为1.4.3

**Comment by linrufeng** [comment]
谢谢我试试先哈
