### ISSUE TITLE
嵌套路由是不是不支持

### ISSUE THREAD

**Issue by axyh** [jaweii/Vueg----page-transition-plugin#47]

**Comment by jaweii** [comment]
vueg是页面级的转场插件，不建议在嵌套路由中使用，可能存在未知的问题。

**Comment by axyh** [comment]
谢谢




            
            
                
                    
                            
                                
                            
                            
                                BigBiu
                            
                    
                        
                            
                                    BigBiu
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年05月29日 11:47，朱嘉伟 写道： Closed #47.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jaweii/Vueg----page-transition-plugin/issues/47?email_source=notifications\u0026email_token=AFZKCUGNENCU26C3JF5HV7LPXX4C7A5CNFSM4HP7U2EKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORV6PGNQ#event-2373776182",
"url": "https://github.com/jaweii/Vueg----page-transition-plugin/issues/47?email_source=notifications\u0026email_token=AFZKCUGNENCU26C3JF5HV7LPXX4C7A5CNFSM4HP7U2EKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORV6PGNQ#event-2373776182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
